### ISSUE TITLE
Add GraphQL schema

### ISSUE THREAD

**Issue by edd** [vegaprotocol/api-clients#117]
The current API clients are all generated from the protos. We also have a GraphQL schema file in core that would be useful to have access to for developers interested in that API. Let's add it here.

# Tasks
- [ ] Add a new folder, `/graphql/`
- [ ] Clone schema in to `/graphql/`
- [ ] Auto-generate docs from the schema file using [graphqldoc](https://www.npmjs.com/package/graphqldoc) (`graphqldoc -s path/to/schema.graphql -o graphql_output_dir/`)

Nothing more needs to be done at the moment.

@cdm has pointed out that the GraphQL schema isn't really a *client*, which is true. Currently there is no plan to build GraphQL based clients in any language, but as Vega Console uses GraphQL it's possible that that functionality could be split out, in which case it would be added here. Feel free to leave a comment if that would be useful.
